export const CREATE_SHIRT = 'CREATE_SHIRT';
export const DELETE_SHIRT = 'DELETE_SHIRT';
export const UPDATE_SHIRT = 'UPDATE_SHIRT';
export const REQUEST_SHIRTS = 'REQUEST_SHIRTS';
export const REQUEST_SHIRTS_SUCCESS = 'REQUEST_SHIRTS_SUCCESS';
export const REQUEST_SHIRTS_FAILURE = 'REQUEST_SHIRTS_FAILURE';
export const CREATE_USER = 'CREATE_USER';